// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Orb: typeof import('./src/components/Orb.vue')['default']
    PatternBackground: typeof import('./src/components/ui/pattern-background/PatternBackground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
